### ISSUE TITLE
Create a flatpak and publish on flathub

### ISSUE THREAD

**Issue by Jacalz** [Jacalz/rymdport#23]
### Description:
This is a kind of progress report issue on trying to get wormhole-gui working as a flatpak. I have a manifest below that manages to build it without complaining too much.

### Further work

- [x] Switch the app-id and all relevant files to "io.github.jacalz.wormhole_gui".
- [x] Use module vendor to comply with stricter build configs without network support.
- [x] Make the file system access a bit less strict (more than just the documents folder).
- [x] Add access to the fyne settings files.
- [x] Make the notifications work (some kind of dbus issue or might need to use the portal: https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.Notification).
- [ ] Work upstream with Fyne on potentially better flatpak support (if needed).

### Manifest
```yml
app-id: io.github.jacalz.rymdport
runtime: org.freedesktop.Platform
runtime-version: '21.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
    - org.freedesktop.Sdk.Extension.golang
command: rymdport

finish-args:
    - --share=ipc # Share IPC namespace with the host (necessary for X11).
    - --share=network
    - --socket=x11
    - --device=dri # OpenGL rendering support.

    # The below are commented out until there is out of the box support for wayland.
    #- --socket=fallback-x11 # Only create the x11 socket if wayland isn't avaliable.
    #- --socket=wayland

    # Needed to support desktop notifications.
    - --talk-name=org.freedesktop.Notifications

    # Support only the most common directories.
    - --filesystem=xdg-desktop
    - --filesystem=xdg-documents
    - --filesystem=xdg-download
    - --filesystem=xdg-music
    - --filesystem=xdg-pictures
    - --filesystem=xdg-videos

build-options:
  env:
    - GOBIN=/app/bin
    - GOROOT=/usr/lib/sdk/golang

modules:
    - name: rymdport
      buildsystem: simple
      build-commands:
        - $GOROOT/bin/go build -ldflags="-s -w" -o rymdport
        - install -Dm00755 rymdport $FLATPAK_DEST/bin/rymdport
        - install -Dm00644 internal/assets/icon/icon-512.png $FLATPAK_DEST/share/icons/hicolor/512x512/apps/$FLATPAK_ID.png
        - install -Dm00644 internal/assets/svg/icon.svg $FLATPAK_DEST/share/icons/hicolor/scalable/apps/$FLATPAK_ID.png
        - install -Dm00644 internal/assets/unix/$FLATPAK_ID.desktop $FLATPAK_DEST/share/applications/$FLATPAK_ID.desktop
        - install -Dm00644 internal/assets/unix/$FLATPAK_ID.appdata.xml $FLATPAK_DEST/share/appdata/$FLATPAK_ID.appdata.xml
      sources:
        - type: archive
          url: "https://github.com/Jacalz/rymdport/releases/download/v3.0.1/rymdport-v3.0.1.tar.xz"
          sha256: 7fcc0d7dce44a590796aa446bdb8a6c9365c453dde64e46477f041b6a48b37a7
```
